# Generated by Django 5.2.5 on 2025-08-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_tasks_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Tasks',
            fields=[
                ('tasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo_app.tasks')),
            ],
            options={
                'verbose_name': 'Выполненная задача',
                'verbose_name_plural': 'Выполненные задачи',
            },
            bases=('todo_app.tasks',),
        ),
    ]
