# Generated by Django 5.2.5 on 2025-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_tasks_done_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Задача выполнена'),
        ),
        migrations.DeleteModel(
            name='Completed_Tasks',
        ),
    ]
