# Generated by Django 5.2.5 on 2025-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_tasks_done_delete_completed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completion_time',
            field=models.DateTimeField(default='2025-08-30 0:0', verbose_name='Задача выполнена в:'),
        ),
    ]
