# Generated by Django 5.2.5 on 2025-08-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_tasks_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Задача выполнена в:'),
        ),
    ]
